### PR TITLE
feat: add holidays option

### PR DESCRIPTION
**Pull request by rfoel**
Adds an option to pass an array with holidays and a date format. 

I tried to do something like the [moment-business-days](https://github.com/kalmecak/moment-business-days) but I couldn't find a way to work with the [UpdateLocale](https://day.js.org/docs/en/plugin/update-locale) and [LocaleData](https://day.js.org/docs/en/plugin/locale-data) to add the holidays and access them by Day.js class.

My solution was to use the options parameter, which does the job as well but not as elegant. 

Waiting for some feedback!

### CODE REVIEW

**Comment by rfoel** [comment]
Someone? @chris-soar @bobbysoar @ConorWatsonSoar @janesoar

**Comment by RBrNx** [comment]
Hey @rfoel, I am the original creator of this plugin for Soar (@ConorWatsonSoar). Unfortunately I have now left Soar and I no longer have write access to this repository.

I am unsure if Soar will continue to maintain this Plugin.

The PR looks good though, I would recommend someone at Soar to merge it 👍

**Comment by rfoel** [comment]
@RBrNx I understand. I'm gonna need this plugin soon, but seems as the plugin is new and not highly used it's not been taken care of. Probably I will make a fork out of this and publish privately. 

Thanks for the reply though.

**Comment by paultheurer-soar** [comment]
Thanks for the contribution @rfoel - Apologies for the delay in reviewing this!

**Comment by rfoel** [comment]
Thank you guys. Any plans on releasing this?

**Pull request merged**
